"""Static project files written into every scaffolded game.

These are the toolchain/config files a professional Rojo-based Roblox project
needs. The generated Luau lives in ``src/``; these wire it up so it opens in
Studio (via Rojo) and lints/formats with the standard community tools.
"""

from __future__ import annotations


def default_project_json(name: str) -> str:
    """A Rojo ``default.project.json`` mapping ``src/`` into the DataModel.

    Layout: src/shared -> ReplicatedStorage.Shared, src/server ->
    ServerScriptService.Server, src/client -> StarterPlayer.StarterPlayerScripts.
    """
    return f"""{{
  "name": "{name}",
  "tree": {{
    "$className": "DataModel",
    "ReplicatedStorage": {{
      "Shared": {{ "$path": "src/shared" }}
    }},
    "ServerScriptService": {{
      "Server": {{ "$path": "src/server" }}
    }},
    "StarterPlayer": {{
      "StarterPlayerScripts": {{
        "Client": {{ "$path": "src/client" }}
      }}
    }},
    "Workspace": {{
      "$properties": {{ "FilteringEnabled": true }}
    }}
  }}
}}
"""


# rokit (the modern aftman successor) pins the toolchain so collaborators and CI
# all use the same Rojo/Selene/StyLua versions.
ROKIT_TOML = """\
# Toolchain pinned with rokit (https://github.com/rojo-rbx/rokit)
# Install rokit, then run `rokit install` in this directory.
[tools]
rojo = "rojo-rbx/rojo@7.4.4"
selene = "Kampfkarren/selene@0.27.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
"""

WALLY_TOML = """\
[package]
name = "robloxforge/game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Add packages here, e.g. a data library:
# ProfileStore = "loleris/profilestore@1.0.0"
"""

SELENE_TOML = """\
std = "roblox"
"""

LUAURC = """\
{
  "languageMode": "strict",
  "lintErrors": true,
  "globals": ["game", "workspace", "script", "shared"]
}
"""


def game_readme(name: str, pitch: str) -> str:
    return f"""# {name}

{pitch}

## Built by RobloxForge

This project was generated by the RobloxForge AI pipeline. The `forge/` folder
contains the market report, game design document, QA report, and launch plan.

## Open in Studio

This is a [Rojo](https://rojo.space) project.

```sh
rokit install         # installs Rojo, Selene, StyLua (see rokit.toml)
rojo serve            # then connect from the Rojo Studio plugin
```

Or build a place file directly:

```sh
rojo build -o {name}.rbxlx
```

## Lint & format

```sh
selene src
stylua src
```

## Source layout

| Path         | Maps to (in Studio)                         |
|--------------|---------------------------------------------|
| `src/shared` | `ReplicatedStorage.Shared`                  |
| `src/server` | `ServerScriptService.Server`                |
| `src/client` | `StarterPlayer.StarterPlayerScripts.Client` |
"""
